# Service LoadBalancer para Pagamento
apiVersion: v1
kind: Service
metadata:
  name: pagamento-service
  labels:
    app: pagamento
    component: service
spec:
  type: LoadBalancer
  selector:
    app: pagamento
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP